### ISSUE TITLE
User can login

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-7/nutshell-vaulted-ceilings#2]
# Story

As a user, I should be able to login to nutshell.

# Acceptance Criteria

**Given** a user wants to use Nutshell
**Then** the user should see a login screen
**And** they should enter their username and password
**And** they should be taken to their dashboard

**Comment by annamd115** [comment]
<img width="502" alt="screen shot 2018-06-12 at 11 22 46 am" src="https://user-images.githubusercontent.com/23087466/41303722-b0be80ca-6e33-11e8-810e-001df7779ec1.png">
<img width="496" alt="screen shot 2018-06-12 at 11 26 16 am" src="https://user-images.githubusercontent.com/23087466/41303726-b3688c1c-6e33-11e8-9496-204f18e44a73.png">
